# Generated by Django 2.2.14 on 2020-07-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200724_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.TextField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fapkpure.com%2Fanime-girl-kawaii%2Fcom.suadah0611.animegirlkawaiiapp&psig=AOvVaw0oSX50FEMim7Zrnb0K0TTN&ust=1596068942960000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCPjN86aa8eoCFQAAAAAdAAAAABAI'),
        ),
    ]
