# Generated by Django 2.2.14 on 2020-07-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.TextField(default='https://i.imgur.com/wBk6SwF_d.webp?maxwidth=728&fidelity=grand'),
        ),
    ]
