# Generated by Django 2.2.14 on 2020-07-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.TextField(default='https://i.kym-cdn.com/photos/images/facebook/001/430/011/c1d.png'),
        ),
    ]
